# This file is managed by 'repo_helper'. Don't edit it directly.
# Read the Docs configuration file
---
version: 2
sphinx:
  builder: html
  configuration: doc-source/conf.py
formats: all
python:
  version: 3.8
  install:
   - requirements: requirements.txt
   - requirements: doc-source/requirements.txt
