# This file is managed by 'repo_helper'. Don't edit it directly.
# Read the Docs configuration file
---
version: 2
sphinx:
  builder: html
  configuration: doc-source/conf.py
formats:
 - pdf
 - htmlzip
python:
  install:
   - requirements: requirements.txt
   - requirements: doc-source/requirements.txt
   - requirements: doc-source/rtd-extra-deps.txt
build:
  os: ubuntu-20.04
  tools:
    python: '3.9'
  jobs:
    post_create_environment:
     - pip install .[all]
