# This file is managed by 'repo_helper'. Don't edit it directly.
# Read the Docs configuration file
---
version: 2
sphinx:
  builder: html
  configuration: doc-source/conf.py
formats:
 - pdf
 - htmlzip
python:
  install:
   - requirements: requirements.txt
   - requirements: doc-source/requirements.txt
   - requirements: doc-source/rtd-extra-deps.txt
build:
  os: ubuntu-20.04
  tools:
    python: '3.9'
  jobs:
    post_create_environment:
     - pip install .[all]
    post_install:
     - pip install sphinxcontrib-applehelp==1.0.4 sphinxcontrib-devhelp==1.0.2 sphinxcontrib-htmlhelp==2.0.1
       sphinxcontrib-jsmath==1.0.1 sphinxcontrib-qthelp==1.0.3 sphinxcontrib-serializinghtml==1.1.5
